services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    environment:
      DATABASE_URL: postgres://example:example@db:5432/example?sslmode=disable
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env.example

volumes:
  dbdata:

